server:
  port: 8082

iot:
  auth:
    excludePaths:
      - /**/login/**
      - /**/token
      - /**/RSA/**
      - /swagger-ui/**
      - /doc.html#/home
      - /swagger-resources/**
      - /webjars/**
      - /v3/**
      - /api/**
      - /swagger-ui.html/**
      - /**/v3/**
      - /**/api/**
      - /**/android/**
      - /**/sse/**
      - /**/control/**

spring:
  servlet:
    multipart:
      max-file-size: 50MB